tenant_id             = "tnt-mike-pietruszka"
project_id            = "prj-g-tfseed-4200"
tenant_project_number = "128178624758"
region                = "us-central1"
zone                  = "us-central1-a"
machine_type          = "e2-medium"
